// ManageComingSoon - Add Movie Task
// Scheduled task that processes the AddMovieTracker queue serially.
// Triggered programmatically by AddMoviePageView via ITaskManager.
//
// Key design decisions:
//   • UI updates are fully event-driven — no poll timer.
//   • AddMovieTracker state methods (SetAdding, SetAddingPercent, SetAdded,
//     SetAddFailed) fire OnItemStateChanged after each mutation. The task
//     wires OnItemStateChanged in SetDependencies so the correct event fires
//     without callers having to remember to pair tracker calls with events.
//   • itemProgress calls SetAddingPercent only — it does NOT call SetAdding
//     — that avoids the race where a late Progress<T> Post fires after SetAdded.
//   • onStatus is the sole driver of AddingDetail text, called synchronously
//     from the pipeline on the task thread so it cannot race with SetAdded.
//   • OperationCanceledException mid-pipeline transitions via SetAddFailed
//     first (to satisfy SetQueued's state guard) then immediately re-queues.
//
// Two independent progress dials, deliberately decoupled:
//   • Admin task-manager bar (the outer IProgress<double>) reflects queue
//     position only — it advances by exactly one slice per item, reported
//     right before the item starts and right after it reaches a terminal
//     state (Added or AddFailed). It has no knowledge of pipeline internals.
//   • Row UI progress (AddMovieTracker.SetAddingPercent) reflects the
//     pipeline's own real milestones (see EmbyLibraryAddService's
//     AddComingSoonStagePercent: ReadinessCheck 5% / WriteFiles 30% /
//     RefreshTargetLibrary 40% / ConfirmIngestedAndTagged 95% / Complete
//     100%). These are genuine stage boundaries, not synthetic — the values
//     stay as-is in EmbyLibraryAddService.
//
// ThrottlePush enforces a minimum gap between tracker-mutating pushes
// generated by this task's own background thread. Several pipeline stages
// (ReadinessCheck → WriteFiles → RefreshTargetLibrary) can complete within
// milliseconds of each other on a fast server, which previously meant the
// client never got a render frame between them — the row's Adding state
// and progress bar were never actually seen before the row moved on. It is
// a *minimum spacing* gate, not a flat per-item delay: if real pipeline time
// has already elapsed since the last push (e.g. across the ConfirmIngested-
// AndTagged wait), it costs nothing. It only ever runs on this task's own
// background thread, never on a RunCommand/HTTP thread, so it never adds
// latency to an interactive button click.

namespace ManageComingSoon.Services
{
    using System;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using MediaBrowser.Common.Net;
    using MediaBrowser.Controller.Providers;
    using MediaBrowser.Controller.Tasks;
    using MediaBrowser.Model.Logging;
    using MediaBrowser.Model.Tasks;

    public class AddMovieTask : IScheduledTask
    {
        private static EmbyLibraryAddService staticLibraryService;
        private static ILogger staticLogger;
        private static Func<string> staticGetApiKey;
        private static Func<string> staticGetTargetPath;
        private static Func<string> staticGetCustomStubPath;

        public static void SetDependencies(
            EmbyLibraryAddService libraryService,
            ILogger logger,
            Func<string> getApiKey,
            Func<string> getTargetPath,
            Func<string> getCustomStubPath)
        {
            staticLibraryService = libraryService;
            staticLogger = logger;
            staticGetApiKey = getApiKey;
            staticGetTargetPath = getTargetPath;
            staticGetCustomStubPath = getCustomStubPath;

            // Wire the single tracker delegate to the single task event.
            // AddMovieTracker fires OnStateChanged from every [UI] mutation method;
            // the page view subscribes to StateChanged and calls RebuildAndBroadcast.
            AddMovieTracker.OnStateChanged = () => StateChanged?.Invoke();
        }

        /// <summary>
        /// Raised by AddMovieTracker after any [UI] state mutation — the single
        /// event the page view subscribes to for all UI refreshes.
        /// Replaces the previous ItemStarted / ItemProgressChanged / ItemCompleted
        /// trio; the tracker fires it from inside each [UI] method so callers
        /// never pair tracker calls with event raises manually.
        /// </summary>
        public static event Action StateChanged;

        public AddMovieTask() { }

        private EmbyLibraryAddService LibraryService => staticLibraryService;
        private ILogger Logger => staticLogger;

        public string Name => "Add Coming Soon Movies";
        public string Description => "Managed by the Manage Coming Soon plugin. Do not schedule manually — trigger via the Add Coming Soon tab only.";
        public string Category => "GinjaNinja Tools";
        public string Key => "ManageComingSoon_AddMovie";

        public IEnumerable<TaskTriggerInfo> GetDefaultTriggers()
            => new TaskTriggerInfo[0];

        // Minimum gap between consecutive items to prevent back-to-back REST
        // refresh calls racing each other when stubs ingest quickly.
        private const int MinGapBetweenItemsSeconds = 5;

        // Minimum gap enforced between tracker-mutating pushes generated by
        // this task's own background thread — see header comment.
        private const int MinPushGapMs = 200;
        private readonly object pushGate = new object();
        private DateTime lastPushUtc = DateTime.MinValue;

        private void ThrottlePush()
        {
            lock (this.pushGate)
            {
                var wait = MinPushGapMs - (DateTime.UtcNow - this.lastPushUtc).TotalMilliseconds;
                if (wait > 0)
                    Thread.Sleep((int)wait);
                this.lastPushUtc = DateTime.UtcNow;
            }
        }

        public async Task Execute(CancellationToken cancellationToken, IProgress<double> progress)
        {
            var items = AddMovieTracker.DequeueAllQueued();

            if (items.Length == 0)
            {
                this.Logger.Info("ManageComingSoon: AddMovieTask started but queue is empty — nothing to do.");
                progress.Report(100);
                return;
            }

            string apiKey = staticGetApiKey != null ? staticGetApiKey() : null;
            string targetPath = staticGetTargetPath != null ? staticGetTargetPath() : null;
            string customStubPath = staticGetCustomStubPath != null ? staticGetCustomStubPath() : null;

            if (string.IsNullOrEmpty(apiKey))
                this.Logger.Warn("ManageComingSoon: AddMovieTask starting with NO Emby API key — " +
                    "every item will fail at the library-refresh stage. Set it on the Configuration tab.");

            if (string.IsNullOrEmpty(targetPath))
            {
                this.Logger.Warn("ManageComingSoon: AddMovieTask starting with NO target path — " +
                    "failing all {0} item(s) immediately.", items.Length);
                foreach (var doomed in items)
                    AddMovieTracker.SetAddFailed(doomed.Id,
                        "No target library path configured. Set one on the Configuration tab.");
                progress.Report(100);
                return;
            }

            this.Logger.Info("ManageComingSoon: AddMovieTask starting — {0} item(s) to process.", items.Length);

            int successCount = 0;
            int failCount = 0;

            for (int i = 0; i < items.Length; i++)
            {
                if (cancellationToken.IsCancellationRequested)
                {
                    this.Logger.Warn(
                        "ManageComingSoon: AddMovieTask cancelled — {0} item(s) remaining left Queued for resume.",
                        items.Length - i);
                    break;
                }

                // Capture loop variables so closures below are unambiguous.
                var item = items[i];
                int itemIndex = i;
                double sliceStart = (double)itemIndex / items.Length * 100.0;
                double sliceSize = 100.0 / items.Length;

                this.Logger.Info("ManageComingSoon: AddMovieTask processing [{0}/{1}] '{2}'",
                    itemIndex + 1, items.Length, item.ConfirmedTitle);

                // Admin task-manager bar: queue position only, independent of
                // pipeline internals and independent of the row UI.
                progress.Report(sliceStart);

                // Transition to Adding — fires OnStateChanged so the row shows
                // the spinner and progress bar. ThrottlePush guarantees this and
                // every subsequent push below get at least MinPushGapMs apart,
                // so the pipeline's rapid early stages (ReadinessCheck 5% →
                // WriteFiles 30% → RefreshLibrary 40%, which can complete within
                // milliseconds of each other) each still get a render frame,
                // without taxing every item a flat delay regardless of real work.
                ThrottlePush();
                AddMovieTracker.SetAdding(item.Id, AddMovieTracker.StepWritingFiles,
                    "Writing folder and stub file\u2026");

                DateTime itemStart = DateTime.UtcNow;

                // Races the pipeline against ComingSoonEntryPoint's ItemAdded
                // fast path (see AddMovieTracker.NotifyPathConfirmed). Both are
                // legitimate, independent observers of the same real-world
                // event — whichever confirms first wins, and the other stops
                // rather than duplicating work neither the user nor the
                // system needs done twice.
                using (var itemCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken))
                {
                    var fastPathTcs = new TaskCompletionSource<bool>(
                        TaskCreationOptions.RunContinuationsAsynchronously);

                    // itemProgress/onStatus are defined here (inside the using,
                    // after itemCts exists) so they can check itemCts's own
                    // cancellation — not the outer cancellationToken — before
                    // doing anything. Without this, an orphaned pipeline call
                    // that's slow to unwind after itemCts.Cancel() keeps calling
                    // these, and each call contends ThrottlePush's shared lock,
                    // stalling the NEXT item's legitimate broadcasts behind
                    // this item's now-pointless background noise.
                    var itemProgress = new Progress<double>(p =>
                    {
                        if (itemCts.IsCancellationRequested) return;
                        ThrottlePush();
                        AddMovieTracker.SetAddingPercent(item.Id, (int)p);
                    });

                    Action<string> onStatus = msg =>
                    {
                        if (itemCts.IsCancellationRequested) return;
                        ThrottlePush();
                        AddMovieTracker.SetAdding(item.Id, AddMovieTracker.StepAwaitingIngest, msg);
                    };

                    // Watches AddMovieTracker.IsPathConfirmed rather than State —
                    // ComingSoonEntryPoint only signals confirmation now, it no
                    // longer mutates State itself. AddMovieTask is the sole
                    // writer of terminal transitions; this just tells it when
                    // it's safe to stop its own pipeline and apply completion.
                    Action checkFastPath = () =>
                    {
                        if (AddMovieTracker.IsPathConfirmed(item.Id))
                            fastPathTcs.TrySetResult(true);
                    };

                    AddMovieTracker.OnStateChanged += checkFastPath;
                    try
                    {
                        // Covers the case where the fast path already landed
                        // between SetAdding above and subscribing here.
                        checkFastPath();

                        var movie = new ManageComingSoon.Model.TmdbMovieResult
                        {
                            Id = item.ConfirmedTmdbId,
                            Title = item.ConfirmedTitle,
                            Overview = item.ConfirmedOverview,
                            ReleaseDate = item.ConfirmedYear > 0
                                ? item.ConfirmedYear.ToString() + "-01-01"
                                : string.Empty,
                            PosterPath = item.ConfirmedPosterPath,
                        };

                        var pipelineTask = this.LibraryService.AddComingSoonPipelineAsync(
                            movie, targetPath, customStubPath, apiKey,
                            itemProgress, onStatus, itemCts.Token);

                        var winner = await Task.WhenAny(pipelineTask, fastPathTcs.Task)
                            .ConfigureAwait(false);

                        if (winner == fastPathTcs.Task)
                        {
                            // Fast path won — stop the now-redundant pipeline.
                            // Its own polling will observe the cancellation and
                            // unwind; we don't need its result. Any fault it
                            // raises afterward is logged, not acted on, so it
                            // never surfaces as an unobserved task exception.
                            itemCts.Cancel();
                            _ = pipelineTask.ContinueWith(t =>
                            {
                                if (t.IsFaulted)
                                    this.Logger.Warn(
                                        "ManageComingSoon: AddMovieTask [{0}/{1}] '{2}' — pipeline raised after fast-path short-circuit (harmless): {3}",
                                        itemIndex + 1, items.Length, item.ConfirmedTitle,
                                        t.Exception.GetBaseException().Message);
                            }, TaskScheduler.Default);

                            // ComingSoonEntryPoint only signaled confirmation —
                            // it never touched State. AddMovieTask applies the
                            // actual completion here, exactly as it would if
                            // its own pipeline had won instead. This is the
                            // only call to SetAdded for the fast-path-win case;
                            // SetAdded's own guard and minimum-visible-dwell
                            // deferral apply exactly as usual.
                            // item.AddedFolderPath is already populated (set
                            // well before Adding, during the destination-
                            // conflict check at Confident/Queued time) — NOT
                            // the shared library-root targetPath variable,
                            // which is the same value for every item in this
                            // run and would be wrong here.
                            ThrottlePush();
                            AddMovieTracker.SetAdded(item.Id, item.AddedFolderPath);
                            this.Logger.Info(
                                "ManageComingSoon: AddMovieTask [{0}/{1}] '{2}' — path confirmed by ComingSoonEntryPoint; applying completion.",
                                itemIndex + 1, items.Length, item.ConfirmedTitle);
                            successCount++;

                            progress.Report(sliceStart + sliceSize);
                        }
                        else
                        {
                            var result = await pipelineTask.ConfigureAwait(false);

                            // Record folder path before transitioning state so that
                            // ComingSoonEntryPoint.OnItemAdded can match the path if
                            // it fires asynchronously on a parallel thread.
                            AddMovieTracker.RecordFolderPath(item.Id, result.FolderPath);

                            // The row reaching its terminal state and the admin tick
                            // advancing are the same event — reported back to back,
                            // not derived from anything internal to the row's own
                            // progress. This is the single boundary shared by both
                            // dials: sliceStart when the item begins, sliceStart +
                            // sliceSize the moment it lands on Added or AddFailed.
                            if (result.Success)
                            {
                                ThrottlePush();
                                AddMovieTracker.SetAdded(item.Id, result.FolderPath);
                                this.Logger.Info(
                                    "ManageComingSoon: AddMovieTask [{0}/{1}] '{2}' — succeeded.",
                                    itemIndex + 1, items.Length, item.ConfirmedTitle);
                                successCount++;
                            }
                            else
                            {
                                ThrottlePush();
                                AddMovieTracker.SetAddFailed(item.Id,
                                    string.Format("Add failed ({0}): {1}",
                                        result.FailedAtStage, result.FailureReason));
                                this.Logger.Warn(
                                    "ManageComingSoon: AddMovieTask [{0}/{1}] '{2}' — failed at stage {3}: {4}",
                                    itemIndex + 1, items.Length, item.ConfirmedTitle,
                                    result.FailedAtStage, result.FailureReason);
                                failCount++;
                            }
                            progress.Report(sliceStart + sliceSize);
                        }
                    }
                    catch (OperationCanceledException)
                    {
                        this.Logger.Warn(
                            "ManageComingSoon: AddMovieTask [{0}/{1}] '{2}' — cancelled mid-pipeline; re-queued.",
                            itemIndex + 1, items.Length, item.ConfirmedTitle);
                        // SetQueued only accepts Confident/AddFailed — go via
                        // AddFailed to satisfy the guard, then immediately re-queue.
                        AddMovieTracker.SetAddFailed(item.Id, "Cancelled — will resume on next Add All.");
                        AddMovieTracker.SetQueued(item.Id);
                        // No admin tick — the item isn't terminal, it's back in
                        // the queue for the next Add All run.
                        break;
                    }
                    catch (Exception ex)
                    {
                        this.Logger.ErrorException(
                            "ManageComingSoon: AddMovieTask [{0}/{1}] '{2}' — unexpected exception",
                            ex, itemIndex + 1, items.Length, item.ConfirmedTitle);
                        AddMovieTracker.SetAddFailed(item.Id,
                            string.Format("Add failed: {0} — see server log", ex.Message));
                        failCount++;
                        // Still a terminal state for this item — tick the admin
                        // bar so an unexpected exception doesn't stall it.
                        progress.Report(sliceStart + sliceSize);
                    }
                    finally
                    {
                        // Critical: without this, every item leaks a handler
                        // onto AddMovieTracker's static OnStateChanged event —
                        // by the end of a long queue, or across repeated runs,
                        // every past item's stale checkFastPath would still be
                        // firing on every future state change.
                        AddMovieTracker.OnStateChanged -= checkFastPath;
                    }
                } // end using (itemCts)

                // Enforce minimum gap between items. Skipped after the last item.
                if (itemIndex < items.Length - 1 && !cancellationToken.IsCancellationRequested)
                {
                    var elapsed = DateTime.UtcNow - itemStart;
                    var minGap = TimeSpan.FromSeconds(MinGapBetweenItemsSeconds);
                    if (elapsed < minGap)
                    {
                        var waitFor = minGap - elapsed;
                        this.Logger.Info(
                            "ManageComingSoon: AddMovieTask [{0}/{1}] '{2}' completed in {3:0}ms — " +
                            "holding {4:0}ms before starting next item (MinGapBetweenItemsSeconds={5}s floor).",
                            itemIndex + 1, items.Length, item.ConfirmedTitle,
                            elapsed.TotalMilliseconds, waitFor.TotalMilliseconds, MinGapBetweenItemsSeconds);
                        try
                        {
                            await Task.Delay(waitFor, cancellationToken)
                                .ConfigureAwait(false);
                        }
                        catch (OperationCanceledException)
                        {
                            break;
                        }
                    }
                }
            }

            progress.Report(100);
            this.Logger.Info(
                "ManageComingSoon: AddMovieTask complete — {0} succeeded, {1} failed.",
                successCount, failCount);

            // Fire a single Default refresh on the library after all items are
            // done. This lets Emby fetch metadata, artwork, and provider info for
            // all newly added stubs in one pass, without any of it racing the
            // per-item ValidationOnly ingest confirmation. Default mode fetches
            // what's missing without replacing anything already present.
            if (successCount > 0)
            {
                try
                {
                    var postQueueTargetPath = staticGetTargetPath != null ? staticGetTargetPath() : null;
                    var apiKeyForRefresh = staticGetApiKey != null ? staticGetApiKey() : null;

                    if (!string.IsNullOrEmpty(postQueueTargetPath) && !string.IsNullOrEmpty(apiKeyForRefresh))
                    {
                        var http = await this.LibraryService.ResolveHttpAsync(
                            apiKeyForRefresh, "AddMovieTask/PostQueueRefresh",
                            CancellationToken.None).ConfigureAwait(false);

                        if (http != null)
                        {
                            var library = this.LibraryService.FindCollectionFolderPublic(postQueueTargetPath);
                            if (library != null)
                            {
                                await this.LibraryService.CallRefreshEndpointAsync(
                                    http.Value.Client, http.Value.BaseUrl,
                                    library.InternalId, "Library (Coming Soon, post-queue metadata)",
                                    apiKeyForRefresh, MetadataRefreshMode.FullRefresh,
                                    "AddMovieTask/PostQueueRefresh",
                                    CancellationToken.None).ConfigureAwait(false);

                                this.Logger.Info(
                                    "ManageComingSoon: AddMovieTask post-queue Default refresh fired on library InternalId={0}.",
                                    library.InternalId);
                            }
                        }
                    }
                }
                catch (Exception ex)
                {
                    this.Logger.Warn(
                        "ManageComingSoon: AddMovieTask post-queue refresh failed (non-fatal — " +
                        "metadata will appear on the next scheduled scan): {0}", ex.Message);
                }
            }
        }
    }
}